name: Build and Deploy
on:
  repository_dispatch:
    types: [content_update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout platform
        uses: actions/checkout@v2

      - name: Create temporary content directory
        run: mkdir -p temp_content

      - name: Checkout content
        uses: actions/checkout@v2
        with:
          repository: erofteev-dev/content
          path: temp_content

      - name: Move articles to src directory
        run: |
          mkdir -p src/content
          mv temp_content/content/* src/content/
          rm -rf temp_content

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Clean up content
        run: rm -rf src/content
